var mesajlar = {
   silinmeesnasindahata:'Silinme esnasında bir hata meydana geldi',
   islemsirasindahata:'İşlem sırasında bir hata meydana geldi',
   aktivitesilinecek:'Aktivite silinecek emin misin ?',
   begenmektenvazgec:'Beğenmekten vazgeç',
   begen:'Beğen',
   begenisayisi:'Beğeni sayısı',
   odevgonderimikapatilacak:'Emin misin ?',
   islemtamam:'İşlem Tamam',
   derssecilmedi:'Vereceğin ödev için bir ders seçmelisin.',
   basliksecilmedi:'Başlık seçilmedi',
   odevbasariylaeklendi:'Ödev başarıyla eklendi',
   verilmesirasindabirhataolustu:'Ödev verilirken bir hata oluştu.',   
   islemsirasindabirhataolustu:'İşlem sırasında bir hata oluştu.',
   dosyaboyutubuyuk:'Seçtiğin dosyanın boyutu çok büyük',
   dosyaicinyetersizalan:'Bu dosyayı yükleyebilmek için yeterli depolama alanı yok. Depolama alanınızı arttırmak için lütfen hesap türünüzü yükseltin.',
   dosyasecilmedi:'Dosya seçmediniz.',
   dosyabasariylaeklendi:'Dosyayı başarıyla ekledin',
   dosyaeklenirkenhata:'Dosya eklenirken bir hata oluştu.',
   odevinaciklamasicokbuyuk:'Ödevin açıklamasının boyutu 100KB tan büyük olamaz',
   dersiolusturuldu:' dersi oluşturuldu',
   dersadibos:'Hata: Ders adı boş bırakılamaz',

   erisimkodugirilmedi:'Erişim kodunu girmedin',
   dersekatilimbasarisizoldu:'Derse katılımın başarısız oldu. Lütfen erişim kodunu kontrol et.'
};
