var mesajlar = {
    yeniparolagirilmedi:'Enter password',
    gecerliparolagirilmedi:'Enter current password',
    yeniparolatekrargirilmedi:'Re-Enter new password',
    girilenparolalaruyusmadi:'Passwords you have entered are mismatch ',
    parolabasariyladegistirildi:'Password was changed successfully',
    islemtamam:'OK',
    paroladegistirmedehata:'Current password is wrong',
    profilfotograficokbuyuk:'Photo you have selected is too big',
    gecersizdosyaformati:'Invalid file format',
    profilfotografisec:'Select photo',
    adveyasoyadgirilmedi:'Enter name or surname',
    profilbilgileriguncellendi:'Profile was updated successfully',
    islemsirasindahatameydanageldi:'Unexpected error !',
    epostaadresigirilmedi:'Enter e-mail',
    parolagirilmedi:'Enter password',
    geciciparolaepostayagonderildi:'Temporary password was sent to your e-mail',
    epostakayitlidegildi:'E-mail you have entered is not registered',
    islemsirasindabirhata:'Unexpected error',
    adgirilmedi:'Enter your name',
    soyadgirilmedi:'Enter your surname',
    parolatekrargir:'Re-enter your password',
    egitmenkayitkodugir:'Enter instructer verification code'
};

