var mesajlar = {
    yeniparolagirilmedi:'Yeni parola girilmedi',
    gecerliparolagirilmedi:'Geçerli parola girilmedi',
    yeniparolatekrargirilmedi:'Yeni parola tekrar girilmedi',
    girilenparolalaruyusmadi:'Girilen parolalar birbiriyle uyuşmadı.',
    parolabasariyladegistirildi:'Parola başarıyla değiştirildi.',
    islemtamam:'İşlem tamam',
    paroladegistirmedehata:'Parola değiştirilirken hata meydana geldi. Geçerli parola hatalı girildi.',
    profilfotograficokbuyuk:'Seçilen profil fotoğrafı boyutu çok büyük',
    gecersizdosyaformati:'Geçersiz dosya formayı',
    profilfotografisec:'Profil fotoğrafı seç',
    adveyasoyadgirilmedi:'Adını veya soyadını girmedin',
    profilbilgileriguncellendi:'Profil bilgileri güncellendi',
    islemsirasindahatameydanageldi:'İşlem sırasında hata meydana geldi',
    epostaadresigirilmedi:'E-posta adresi girilmedi.',
    parolagirilmedi:'Parola girilmedi',
    geciciparolaepostayagonderildi:'Geçici parola e-posta adresine gönderildi.',
    epostakayitlidegildi:'Girilen e-posta adresi sistemde kayıtlı değil',
    islemsirasindabirhata:'İşlem sırasında bir hata meydana geldi',
    adgirilmedi:'Ad girilmedi',
    soyadgirilmedi:'Soyad girilmedi',
    parolatekrargir:'Parolayı tekrar girin',
    egitmenkayitkodugir:'Eğitmen kayıt kodunu girin'
};
